maidsafe/sn_testnet_tool

Makefile
genesis.tf
node.tf

This looks like it had been commented out for debugging or something like that, but it was preventing SSH from working correctly.
Also change the default number of nodes from 20 to 15, as it can sometimes take quite long to spin up 20 nodes.

fix: Remove Debugging Change

---

node.tf

- d1d3cd1 **fix: Pass `--local-addr` to `sn_node`**
The `sn_node` CLI now defaults to `127.0.0.1` for local address, rather
than `0.0.0.0`, so we need to supply a value if we want external
reachability. We use the node's actual IP rather than `0.0.0.0` due to a
curious behaviour in `sn_node` where it may use the local address as the
public address.

fix: Pass `--local-addr` to `sn_node`

---

down.sh
genesis.tf
node.tf
provider.tf
scripts/get-connection-infos
scripts/register_keys.sh
up.sh

when running the tool on GH actions all files are not created in the
current directory. They are created at $GITHUB_ACTION_PATH. This commit
adds a working_dir variable to the terraform scripts which uses the
GITHUB_ACTION_PATH variable to create and access the files if specified
and defaults to the current dir if undefined (eg. while running locally)

feat(gha-support): add working dir variable

---

build.tf

Errors during installation of musl-tools happens very rarely

refactor(build): move apt update and apt install commands apart to give more time to release the dpkg lock

---

genesis.tf
node.tf

The node was changed to use this more descriptive argument, so `--skip-igd` no longer applies.

chore: use new arg for skipping port forwarding

---

build.tf
genesis.tf
node.tf

- fix(build): add env variable to prevent file-lock failure for apt-get install commands
- feat(tokio-console): set TOKIO_CONSOLE_BIND env variable so the console can be accessed from outside the droplet

Fix file-lock errors and add tokio console support

---

provider.tf

* Use the latest version of the DO provider for Terraform
* Identify who all the SSH key IDs belong to
* Add new SSH key ID for a Github Actions machine user

chore: a few admin tasks

---

scripts/do-delete-droplets.sh

You can run the script using a `--list` argument to see a list of currently running droplets, then
run it using `--name` to remove any droplets starting with a particular string.
Just in case a mistake could have been made with the name, it will prompt for input before removing
anything.

feat: util script for removing droplets

---

node.tf

This argument was removed from the node in the following PR:
https://github.com/maidsafe/safe_network/pull/1137
As a result, all nodes were failing to launch.

feat: remove use of --max-capacity argument

---

.gitignore
.terraform.lock.hcl
Makefile
down.sh
scripts/dl_files.sh
scripts/droplet-operations
scripts/logs
scripts/read-all.sh
scripts/restart.sh
up.sh

- ebabed1 **chore: consistent indentation for scripts**
According to Google's 'Shell Style Guide' (which most use for Bash), two spaces is the recommended
indentation size.
There's also a little fix in the Makefile for referencing shell variables correctly.
- ca04f9f **feat: copy genesis dbc from genesis node**
Also makes some cosmetic changes for readability.

feat: copy genesis dbc from genesis node

---

Makefile
scripts/ELK/install-and-run-metricbeat.sh
scripts/init-node.sh

The installation of various packages produces an enormous amount of text output that is largely of
no interest, and it makes the nightly logs difficult to sift through. Note that I tried various
switches like `-qq`, but there was nothing that worked across different versions of Ubuntu, so I
ended up just redirecting the output to `/dev/null`.
You'd only really be interested in seeing the output when the installs fail, but I'd say in that
case you can turn the output back on to see what is going on. If the package is on apt it should be
pretty stable anyway and an unlikely source of errors.
There are also a couple of changes to the Makefile targets here just to make sure all information
relating to the previous testnet are cleared out.

feat: suppress output from apt

---

.gitignore
down.sh
genesis.tf
node.tf
scripts/init-node.sh
scripts/logs-sync.sh
up.sh

- 530659c **feat(node): provide genesis key from genesis node**
When the genesis node starts up, the genesis key gets output to file by finding it from the logs.
After the Terraform run it will then be copied from the genesis node to the local machine and also
uploaded to S3, as per the IP lists and the prefix map.
Having the genesis key can be useful for basic debugging. We had seen some errors that potentially
indicated a mismatch between the genesis key on the node and the one being used by the client test
runner process.
The down script removed the prefix map and genesis information from S3, but I've taken this out,
since having access to this information could be useful, particularly after a failed nightly run.
There was also a local-exec provisioner that ran to download these files …

Debugging Improvements

---

scripts/logs-sync.sh
up.sh

Based on the `logs` script, this one is very similar, it just operates in a synchronous way rather
than launching rsync in the background.
It's intended to be used mainly for debugging the nightly, so we will want to wait till all the logs
have been downloaded before moving on to the next step.
Note that strict host key checking has been switched off for the rsync. I did try using ssh-keyscan,
but it didn't work in this context.

feat(debug): script for pulling logs

---

scripts/logs-sync.sh

There was a problem with a nightly run where rsync returned an error due to a 'vanished' file, which
is one that was on its transfer list initially, but was subsequently deleted before it actually came
to be transferred. Even though rsync treats this as a warning, it still returns an non-zero exit
code, and you can't change that behaviour using an argument. This caused the run to fail before the
rest of the logs were transferred or the testnet was killed.
I tried a few different methods, but the simplest solution may just be to let the script continue on
errors, so `set -e` is removed.

fix(script): continue on error for log sync

---

Makefile
up.sh

The `NODE_BIN_PATH` argument had been changed to assume a custom binary located at `workspace/${testnet_channel}/sn_node`. However, we still need to be able to use the custom location for use with the testnet custom action. I also personally use full paths to node binaries located in the directory where I have `safe_network` code checked out.
This change will check if the `NODE_BIN_PATH` argument is set, and if not, it will look for a binary in the workspace directory.

fix: retain use of node bin path argument

---

Makefile
aws/ansible/roles/node/templates/sn_node.service.j2
scripts/init-node.sh

The `--first` argument for the node now requires an IP address, and we discovered that it also requires `--local-addr` to be set to `0.0.0.0`.
This has been changed for both DO and AWS. I was able to run a testnet successfully on both providers, using public IP addresses.

chore: configure node for new argument usage

---

.gitignore
aws/Justfile
aws/README.md
aws/ansible/genesis_node.yml
aws/ansible/nodes.yml
aws/ansible/roles/node/defaults/main.yml
aws/ansible/roles/node/tasks/main.yml
aws/ansible/roles/node/templates/sn_node.service.j2

The process for bringing up a testnet with the new `safenode` is as follows:
* Launch all the EC2 instances with Terraform
* Deploy `safenode` on the genesis node
* Use the RPC service to get the peer ID of the genesis node
* Deploy `safenode` on the remaining nodes using the peer ID
It turns out to actually be a bit simpler than the old process.

feat: run testnets on aws with new safenode

---

aws/README.md
aws/ansible/roles/node/defaults/main.yml
aws/ansible/roles/node/templates/sn_node.service.j2

This location will be static while this Opensearch instance remains online.

chore: provide the otlp endpoint

---

run.sh
terraform/digital-ocean/variables.tf
up.sh

- b6e9efc **fix: invalid environment variables**
The `init` and `testnet` targets were passing different environment variables for Digital Ocean.
Also fixes the reference to the container in the run script to prevent the need for building
locally.
- 21efe4d **feat: use ubuntu 22.10 on digital ocean**
There seemed to be some change in the 22.04 base image that was causing locks during an apt-get
update. The same problem doesn't seem present on 22.10.

fix: invalid environment variables

---

Justfile
ansible/extra_vars/digital_ocean.json
ansible/roles/node/defaults/main.yml
ansible/roles/node/tasks/main.yml
ansible/roles/node/templates/sn_node.service.j2
ansible/roles/prerequisites/tasks/main.yml
ansible/roles/rust/tasks/main.yml
terraform/digital-ocean/variables.tf
up.sh

- 243202c **feat: run multiple node services on single vm**
Using systemd it is actually quite simple to run multiple instances of the same service.
It has also been made simple by recent changes we've made in the node for providing default
directories for root and logging, and the fact that the node can select an unused port for us.
- d07b8e7 **feat: change interface to `up.sh` script**
Remove the need to pass a "true" value for indicating use of a custom binary, and just use the
presence of the org and branch arguments.
- 1d6b24d **feat: retries for package installations**
Installing packages with the Ansible module is subject to the same failures as it is in the shell,
namely the dpkg file being locked. A few retries are added, which almost always overcomes the
issue.
Also only run the …

feat: run multiple node services on single vm
